-- Sample data for testing

-- Insert Customers
INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, REGION, SEGMENT, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_CUSTOMER_SEQ, 'North America', 'Enterprise', DATE '2023-01-15');

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, REGION, SEGMENT, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_CUSTOMER_SEQ, 'Europe', 'SMB', DATE '2023-02-20');

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, REGION, SEGMENT, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_CUSTOMER_SEQ, 'Asia Pacific', 'Consumer', DATE '2023-03-10');

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, REGION, SEGMENT, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_CUSTOMER_SEQ, 'North America', 'SMB', DATE '2023-04-05');

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, REGION, SEGMENT, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_CUSTOMER_SEQ, 'Latin America', 'Enterprise', DATE '2023-05-12');

-- Insert Products
INSERT INTO DIM_PRODUCT (PRODUCT_ID, CATEGORY, BRAND, BASE_PRICE, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Electronics', 'TechPro', 1299.99, DATE '2023-01-01');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, CATEGORY, BRAND, BASE_PRICE, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Electronics', 'LogiTech', 49.99, DATE '2023-01-05');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, CATEGORY, BRAND, BASE_PRICE, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Electronics', 'TechPro', 79.99, DATE '2023-02-10');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, CATEGORY, BRAND, BASE_PRICE, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Furniture', 'OfficePro', 399.99, DATE '2023-03-01');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, CATEGORY, BRAND, BASE_PRICE, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Furniture', 'OfficePro', 599.99, DATE '2023-03-15');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, CATEGORY, BRAND, BASE_PRICE, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Electronics', 'KeyMaster', 129.99, DATE '2023-04-01');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, CATEGORY, BRAND, BASE_PRICE, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Electronics', 'DisplayMax', 449.99, DATE '2023-04-10');

INSERT INTO DIM_PRODUCT (PRODUCT_ID, CATEGORY, BRAND, BASE_PRICE, CREATED_DT)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Electronics', 'LogiTech', 89.99, DATE '2023-05-01');

-- Insert Orders
INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_DT, CHANNEL, STATUS)
VALUES (NEXT VALUE FOR FACT_ORDER_SEQ, 1, DATE '2023-06-01', 'Online', 'DELIVERED');

INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_DT, CHANNEL, STATUS)
VALUES (NEXT VALUE FOR FACT_ORDER_SEQ, 2, DATE '2023-06-15', 'Store', 'DELIVERED');

INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_DT, CHANNEL, STATUS)
VALUES (NEXT VALUE FOR FACT_ORDER_SEQ, 3, DATE '2023-07-01', 'Online', 'SHIPPED');

INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_DT, CHANNEL, STATUS)
VALUES (NEXT VALUE FOR FACT_ORDER_SEQ, 1, DATE '2023-07-10', 'Mobile', 'PROCESSING');

INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_DT, CHANNEL, STATUS)
VALUES (NEXT VALUE FOR FACT_ORDER_SEQ, 4, DATE '2023-07-20', 'Online', 'PENDING');

-- Insert Order Lines
INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 1, 1, 100, 1, 1299.99, 0.00);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 1, 2, 101, 1, 49.99, 0.00);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 1, 3, 100, 1, 79.99, 0.00);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 2, 4, 102, 1, 399.99, 0.00);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 2, 5, 102, 1, 599.99, 0.00);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 3, 6, 103, 2, 129.99, 0.00);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 3, 2, 101, 3, 49.99, 0.00);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 3, 3, 100, 1, 79.99, 0.00);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 4, 7, 104, 1, 449.99, 0.00);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 5, 5, 102, 1, 599.99, 10.00);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, SUPPLIER_ID, QTY, UNIT_PRICE, DISCOUNT_PCT)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 5, 7, 104, 1, 449.99, 0.00);
