-- Sample data for testing

-- Insert Customers
INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, COUNTRY, POSTAL_CODE, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_CUSTOMER_SEQ, 'John Smith', 'john.smith@email.com', '+1-555-0101', '123 Main Street', 'New York', 'NY', 'USA', '10001', DATE '2023-01-15', TRUE);

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, COUNTRY, POSTAL_CODE, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_CUSTOMER_SEQ, 'Jane Doe', 'jane.doe@email.com', '+1-555-0102', '456 Oak Avenue', 'Los Angeles', 'CA', 'USA', '90001', DATE '2023-02-20', TRUE);

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, COUNTRY, POSTAL_CODE, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_CUSTOMER_SEQ, 'Bob Johnson', 'bob.johnson@email.com', '+1-555-0103', '789 Pine Road', 'Chicago', 'IL', 'USA', '60601', DATE '2023-03-10', TRUE);

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, COUNTRY, POSTAL_CODE, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_CUSTOMER_SEQ, 'Alice Williams', 'alice.w@email.com', '+1-555-0104', '321 Elm Street', 'Houston', 'TX', 'USA', '77001', DATE '2023-04-05', TRUE);

INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, PHONE, ADDRESS, CITY, STATE, COUNTRY, POSTAL_CODE, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_CUSTOMER_SEQ, 'Charlie Brown', 'charlie.b@email.com', '+1-555-0105', '654 Maple Lane', 'Phoenix', 'AZ', 'USA', '85001', DATE '2023-05-12', FALSE);

-- Insert Products
INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, CATEGORY, SUB_CATEGORY, UNIT_PRICE, DESCRIPTION, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Laptop Pro 15', 'ELEC-LP15', 'Electronics', 'Computers', 1299.99, 'High-performance 15-inch laptop with 16GB RAM', DATE '2023-01-01', TRUE);

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, CATEGORY, SUB_CATEGORY, UNIT_PRICE, DESCRIPTION, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Wireless Mouse', 'ELEC-WM01', 'Electronics', 'Accessories', 49.99, 'Ergonomic wireless mouse with long battery life', DATE '2023-01-05', TRUE);

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, CATEGORY, SUB_CATEGORY, UNIT_PRICE, DESCRIPTION, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'USB-C Hub', 'ELEC-HUB7', 'Electronics', 'Accessories', 79.99, '7-port USB-C hub with HDMI output', DATE '2023-02-10', TRUE);

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, CATEGORY, SUB_CATEGORY, UNIT_PRICE, DESCRIPTION, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Office Chair Deluxe', 'FURN-OCD1', 'Furniture', 'Office', 399.99, 'Ergonomic office chair with lumbar support', DATE '2023-03-01', TRUE);

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, CATEGORY, SUB_CATEGORY, UNIT_PRICE, DESCRIPTION, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Standing Desk', 'FURN-SD48', 'Furniture', 'Office', 599.99, '48-inch electric standing desk', DATE '2023-03-15', TRUE);

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, CATEGORY, SUB_CATEGORY, UNIT_PRICE, DESCRIPTION, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Mechanical Keyboard', 'ELEC-MK01', 'Electronics', 'Accessories', 129.99, 'RGB mechanical keyboard with Cherry MX switches', DATE '2023-04-01', TRUE);

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, CATEGORY, SUB_CATEGORY, UNIT_PRICE, DESCRIPTION, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Monitor 27 4K', 'ELEC-M274K', 'Electronics', 'Monitors', 449.99, '27-inch 4K UHD monitor with HDR', DATE '2023-04-10', TRUE);

INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, PRODUCT_CODE, CATEGORY, SUB_CATEGORY, UNIT_PRICE, DESCRIPTION, CREATED_DATE, ACTIVE_FLAG)
VALUES (NEXT VALUE FOR DIM_PRODUCT_SEQ, 'Webcam HD', 'ELEC-WC1080', 'Electronics', 'Accessories', 89.99, '1080p webcam with built-in microphone', DATE '2023-05-01', FALSE);

-- Insert Orders
INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_NUMBER, ORDER_DATE, STATUS, TOTAL_AMOUNT, TAX_AMOUNT, DISCOUNT_AMOUNT, SHIPPING_ADDRESS, SHIPPED_DATE, DELIVERED_DATE)
VALUES (NEXT VALUE FOR FACT_ORDER_SEQ, 1, 'ORD-2023-001', DATE '2023-06-01', 'DELIVERED', 1429.97, 114.40, 50.00, '123 Main Street, New York, NY 10001', DATE '2023-06-03', DATE '2023-06-07');

INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_NUMBER, ORDER_DATE, STATUS, TOTAL_AMOUNT, TAX_AMOUNT, DISCOUNT_AMOUNT, SHIPPING_ADDRESS, SHIPPED_DATE, DELIVERED_DATE)
VALUES (NEXT VALUE FOR FACT_ORDER_SEQ, 2, 'ORD-2023-002', DATE '2023-06-15', 'DELIVERED', 999.98, 80.00, 0.00, '456 Oak Avenue, Los Angeles, CA 90001', DATE '2023-06-17', DATE '2023-06-21');

INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_NUMBER, ORDER_DATE, STATUS, TOTAL_AMOUNT, TAX_AMOUNT, DISCOUNT_AMOUNT, SHIPPING_ADDRESS, SHIPPED_DATE, DELIVERED_DATE)
VALUES (NEXT VALUE FOR FACT_ORDER_SEQ, 3, 'ORD-2023-003', DATE '2023-07-01', 'SHIPPED', 529.98, 42.40, 25.00, '789 Pine Road, Chicago, IL 60601', DATE '2023-07-03', NULL);

INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_NUMBER, ORDER_DATE, STATUS, TOTAL_AMOUNT, TAX_AMOUNT, DISCOUNT_AMOUNT, SHIPPING_ADDRESS, SHIPPED_DATE, DELIVERED_DATE)
VALUES (NEXT VALUE FOR FACT_ORDER_SEQ, 1, 'ORD-2023-004', DATE '2023-07-10', 'PROCESSING', 449.99, 36.00, 0.00, '123 Main Street, New York, NY 10001', NULL, NULL);

INSERT INTO FACT_ORDER (ORDER_ID, CUSTOMER_ID, ORDER_NUMBER, ORDER_DATE, STATUS, TOTAL_AMOUNT, TAX_AMOUNT, DISCOUNT_AMOUNT, SHIPPING_ADDRESS, SHIPPED_DATE, DELIVERED_DATE)
VALUES (NEXT VALUE FOR FACT_ORDER_SEQ, 4, 'ORD-2023-005', DATE '2023-07-20', 'PENDING', 1049.97, 84.00, 100.00, '321 Elm Street, Houston, TX 77001', NULL, NULL);

-- Insert Order Lines
INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 1, 1, 1, 1299.99, 1299.99, 0.00, 1);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 1, 2, 1, 49.99, 49.99, 0.00, 2);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 1, 3, 1, 79.99, 79.99, 0.00, 3);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 2, 4, 1, 399.99, 399.99, 0.00, 1);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 2, 5, 1, 599.99, 599.99, 0.00, 2);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 3, 6, 2, 129.99, 259.98, 0.00, 1);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 3, 2, 3, 49.99, 149.97, 0.00, 2);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 3, 3, 1, 79.99, 79.99, 0.00, 3);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 4, 7, 1, 449.99, 449.99, 0.00, 1);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 5, 5, 1, 599.99, 599.99, 10.00, 1);

INSERT INTO FACT_ORDER_LINE (ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, LINE_TOTAL, DISCOUNT_PERCENT, LINE_NUMBER)
VALUES (NEXT VALUE FOR FACT_ORDER_LINE_SEQ, 5, 7, 1, 449.99, 449.99, 0.00, 2);
