-- Schema for Oracle Autonomous Database
-- Run this script manually to create tables in Oracle

-- Drop tables if they exist (in reverse order of dependencies)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FACT_ORDER_LINE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FACT_ORDER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DIM_PRODUCT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DIM_CUSTOMER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Drop sequences if they exist
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_CUSTOMER_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_PRODUCT_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE FACT_ORDER_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE FACT_ORDER_LINE_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

-- Create sequences
CREATE SEQUENCE DIM_CUSTOMER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIM_PRODUCT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE FACT_ORDER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE FACT_ORDER_LINE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- DIM_CUSTOMER table
CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER(19) PRIMARY KEY,
    REGION VARCHAR2(100),
    SEGMENT VARCHAR2(100),
    CREATED_DT DATE
);

-- DIM_PRODUCT table
CREATE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER(19) PRIMARY KEY,
    CATEGORY VARCHAR2(100),
    BRAND VARCHAR2(100),
    BASE_PRICE NUMBER(15, 2),
    CREATED_DT DATE
);

-- FACT_ORDER table
CREATE TABLE FACT_ORDER (
    ORDER_ID NUMBER(19) PRIMARY KEY,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    ORDER_DT DATE NOT NULL,
    CHANNEL VARCHAR2(50),
    STATUS VARCHAR2(30),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID)
);

-- FACT_ORDER_LINE table
CREATE TABLE FACT_ORDER_LINE (
    ORDER_LINE_ID NUMBER(19) PRIMARY KEY,
    ORDER_ID NUMBER(19) NOT NULL,
    PRODUCT_ID NUMBER(19) NOT NULL,
    SUPPLIER_ID NUMBER(19),
    QTY NUMBER(10) NOT NULL,
    UNIT_PRICE NUMBER(15, 2),
    DISCOUNT_PCT NUMBER(5, 2),
    CONSTRAINT FK_ORDERLINE_ORDER FOREIGN KEY (ORDER_ID) REFERENCES FACT_ORDER(ORDER_ID),
    CONSTRAINT FK_ORDERLINE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID)
);

-- Create indexes
CREATE INDEX IDX_CUSTOMER_REGION ON DIM_CUSTOMER(REGION);
CREATE INDEX IDX_CUSTOMER_SEGMENT ON DIM_CUSTOMER(SEGMENT);
CREATE INDEX IDX_PRODUCT_CATEGORY ON DIM_PRODUCT(CATEGORY);
CREATE INDEX IDX_PRODUCT_BRAND ON DIM_PRODUCT(BRAND);
CREATE INDEX IDX_ORDER_CUSTOMER ON FACT_ORDER(CUSTOMER_ID);
CREATE INDEX IDX_ORDER_DT ON FACT_ORDER(ORDER_DT);
CREATE INDEX IDX_ORDER_CHANNEL ON FACT_ORDER(CHANNEL);
CREATE INDEX IDX_ORDER_STATUS ON FACT_ORDER(STATUS);
CREATE INDEX IDX_ORDERLINE_ORDER ON FACT_ORDER_LINE(ORDER_ID);
CREATE INDEX IDX_ORDERLINE_PRODUCT ON FACT_ORDER_LINE(PRODUCT_ID);
CREATE INDEX IDX_ORDERLINE_SUPPLIER ON FACT_ORDER_LINE(SUPPLIER_ID);

COMMIT;
