-- Schema for H2 Database (Oracle compatibility mode)
-- This script creates tables compatible with both H2 and Oracle

-- Drop tables if they exist (in reverse order of dependencies)
DROP TABLE IF EXISTS FACT_ORDER_LINE;
DROP TABLE IF EXISTS FACT_ORDER;
DROP TABLE IF EXISTS DIM_PRODUCT;
DROP TABLE IF EXISTS DIM_CUSTOMER;

-- Drop sequences if they exist
DROP SEQUENCE IF EXISTS DIM_CUSTOMER_SEQ;
DROP SEQUENCE IF EXISTS DIM_PRODUCT_SEQ;
DROP SEQUENCE IF EXISTS FACT_ORDER_SEQ;
DROP SEQUENCE IF EXISTS FACT_ORDER_LINE_SEQ;

-- Create sequences
CREATE SEQUENCE DIM_CUSTOMER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DIM_PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FACT_ORDER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FACT_ORDER_LINE_SEQ START WITH 1 INCREMENT BY 1;

-- DIM_CUSTOMER table
CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    REGION VARCHAR(100),
    SEGMENT VARCHAR(100),
    CREATED_DT DATE
);

-- DIM_PRODUCT table
CREATE TABLE DIM_PRODUCT (
    PRODUCT_ID BIGINT PRIMARY KEY,
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    BASE_PRICE DECIMAL(15, 2),
    CREATED_DT DATE
);

-- FACT_ORDER table
CREATE TABLE FACT_ORDER (
    ORDER_ID BIGINT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    ORDER_DT DATE NOT NULL,
    CHANNEL VARCHAR(50),
    STATUS VARCHAR(30),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID)
);

-- FACT_ORDER_LINE table
CREATE TABLE FACT_ORDER_LINE (
    ORDER_LINE_ID BIGINT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    SUPPLIER_ID BIGINT,
    QTY INT NOT NULL,
    UNIT_PRICE DECIMAL(15, 2),
    DISCOUNT_PCT DECIMAL(5, 2),
    CONSTRAINT FK_ORDERLINE_ORDER FOREIGN KEY (ORDER_ID) REFERENCES FACT_ORDER(ORDER_ID),
    CONSTRAINT FK_ORDERLINE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID)
);

-- Create indexes
CREATE INDEX IDX_CUSTOMER_REGION ON DIM_CUSTOMER(REGION);
CREATE INDEX IDX_CUSTOMER_SEGMENT ON DIM_CUSTOMER(SEGMENT);
CREATE INDEX IDX_PRODUCT_CATEGORY ON DIM_PRODUCT(CATEGORY);
CREATE INDEX IDX_PRODUCT_BRAND ON DIM_PRODUCT(BRAND);
CREATE INDEX IDX_ORDER_CUSTOMER ON FACT_ORDER(CUSTOMER_ID);
CREATE INDEX IDX_ORDER_DT ON FACT_ORDER(ORDER_DT);
CREATE INDEX IDX_ORDER_CHANNEL ON FACT_ORDER(CHANNEL);
CREATE INDEX IDX_ORDER_STATUS ON FACT_ORDER(STATUS);
CREATE INDEX IDX_ORDERLINE_ORDER ON FACT_ORDER_LINE(ORDER_ID);
CREATE INDEX IDX_ORDERLINE_PRODUCT ON FACT_ORDER_LINE(PRODUCT_ID);
CREATE INDEX IDX_ORDERLINE_SUPPLIER ON FACT_ORDER_LINE(SUPPLIER_ID);
