-- Schema for Oracle Autonomous Database
-- Run this script manually to create tables in Oracle

-- Drop tables if they exist (in reverse order of dependencies)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FACT_ORDER_LINE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FACT_ORDER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DIM_PRODUCT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DIM_CUSTOMER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Drop sequences if they exist
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_CUSTOMER_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE DIM_PRODUCT_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE FACT_ORDER_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE FACT_ORDER_LINE_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

-- Create sequences
CREATE SEQUENCE DIM_CUSTOMER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DIM_PRODUCT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE FACT_ORDER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE FACT_ORDER_LINE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- DIM_CUSTOMER table
CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_ID NUMBER(19) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(150),
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(500),
    CITY VARCHAR2(100),
    STATE VARCHAR2(100),
    COUNTRY VARCHAR2(100),
    POSTAL_CODE VARCHAR2(20),
    CREATED_DATE DATE,
    ACTIVE_FLAG NUMBER(1) DEFAULT 1
);

-- DIM_PRODUCT table
CREATE TABLE DIM_PRODUCT (
    PRODUCT_ID NUMBER(19) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(200) NOT NULL,
    PRODUCT_CODE VARCHAR2(50) NOT NULL,
    CATEGORY VARCHAR2(100),
    SUB_CATEGORY VARCHAR2(100),
    UNIT_PRICE NUMBER(15, 2),
    DESCRIPTION VARCHAR2(1000),
    CREATED_DATE DATE,
    ACTIVE_FLAG NUMBER(1) DEFAULT 1
);

-- FACT_ORDER table
CREATE TABLE FACT_ORDER (
    ORDER_ID NUMBER(19) PRIMARY KEY,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    ORDER_NUMBER VARCHAR2(50) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    STATUS VARCHAR2(30),
    TOTAL_AMOUNT NUMBER(15, 2),
    TAX_AMOUNT NUMBER(15, 2),
    DISCOUNT_AMOUNT NUMBER(15, 2),
    SHIPPING_ADDRESS VARCHAR2(500),
    SHIPPED_DATE DATE,
    DELIVERED_DATE DATE,
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID)
);

-- FACT_ORDER_LINE table
CREATE TABLE FACT_ORDER_LINE (
    ORDER_LINE_ID NUMBER(19) PRIMARY KEY,
    ORDER_ID NUMBER(19) NOT NULL,
    PRODUCT_ID NUMBER(19) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    UNIT_PRICE NUMBER(15, 2),
    LINE_TOTAL NUMBER(15, 2),
    DISCOUNT_PERCENT NUMBER(5, 2),
    LINE_NUMBER NUMBER(10),
    CONSTRAINT FK_ORDERLINE_ORDER FOREIGN KEY (ORDER_ID) REFERENCES FACT_ORDER(ORDER_ID),
    CONSTRAINT FK_ORDERLINE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID)
);

-- Create indexes
CREATE INDEX IDX_CUSTOMER_NAME ON DIM_CUSTOMER(CUSTOMER_NAME);
CREATE INDEX IDX_CUSTOMER_CITY ON DIM_CUSTOMER(CITY);
CREATE INDEX IDX_PRODUCT_CODE ON DIM_PRODUCT(PRODUCT_CODE);
CREATE INDEX IDX_PRODUCT_CATEGORY ON DIM_PRODUCT(CATEGORY);
CREATE INDEX IDX_ORDER_CUSTOMER ON FACT_ORDER(CUSTOMER_ID);
CREATE INDEX IDX_ORDER_DATE ON FACT_ORDER(ORDER_DATE);
CREATE INDEX IDX_ORDER_NUMBER ON FACT_ORDER(ORDER_NUMBER);
CREATE INDEX IDX_ORDERLINE_ORDER ON FACT_ORDER_LINE(ORDER_ID);
CREATE INDEX IDX_ORDERLINE_PRODUCT ON FACT_ORDER_LINE(PRODUCT_ID);

COMMIT;
