-- Schema for H2 Database (Oracle compatibility mode)
-- This script creates tables compatible with both H2 and Oracle

-- Drop tables if they exist (in reverse order of dependencies)
DROP TABLE IF EXISTS FACT_ORDER_LINE;
DROP TABLE IF EXISTS FACT_ORDER;
DROP TABLE IF EXISTS DIM_PRODUCT;
DROP TABLE IF EXISTS DIM_CUSTOMER;

-- Drop sequences if they exist
DROP SEQUENCE IF EXISTS DIM_CUSTOMER_SEQ;
DROP SEQUENCE IF EXISTS DIM_PRODUCT_SEQ;
DROP SEQUENCE IF EXISTS FACT_ORDER_SEQ;
DROP SEQUENCE IF EXISTS FACT_ORDER_LINE_SEQ;

-- Create sequences
CREATE SEQUENCE DIM_CUSTOMER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DIM_PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FACT_ORDER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FACT_ORDER_LINE_SEQ START WITH 1 INCREMENT BY 1;

-- DIM_CUSTOMER table
CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(150),
    PHONE VARCHAR(30),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    CREATED_DATE DATE,
    ACTIVE_FLAG BOOLEAN DEFAULT TRUE
);

-- DIM_PRODUCT table
CREATE TABLE DIM_PRODUCT (
    PRODUCT_ID BIGINT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    PRODUCT_CODE VARCHAR(50) NOT NULL,
    CATEGORY VARCHAR(100),
    SUB_CATEGORY VARCHAR(100),
    UNIT_PRICE DECIMAL(15, 2),
    DESCRIPTION VARCHAR(1000),
    CREATED_DATE DATE,
    ACTIVE_FLAG BOOLEAN DEFAULT TRUE
);

-- FACT_ORDER table
CREATE TABLE FACT_ORDER (
    ORDER_ID BIGINT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    ORDER_NUMBER VARCHAR(50) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    STATUS VARCHAR(30),
    TOTAL_AMOUNT DECIMAL(15, 2),
    TAX_AMOUNT DECIMAL(15, 2),
    DISCOUNT_AMOUNT DECIMAL(15, 2),
    SHIPPING_ADDRESS VARCHAR(500),
    SHIPPED_DATE DATE,
    DELIVERED_DATE DATE,
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID)
);

-- FACT_ORDER_LINE table
CREATE TABLE FACT_ORDER_LINE (
    ORDER_LINE_ID BIGINT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(15, 2),
    LINE_TOTAL DECIMAL(15, 2),
    DISCOUNT_PERCENT DECIMAL(5, 2),
    LINE_NUMBER INT,
    CONSTRAINT FK_ORDERLINE_ORDER FOREIGN KEY (ORDER_ID) REFERENCES FACT_ORDER(ORDER_ID),
    CONSTRAINT FK_ORDERLINE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID)
);

-- Create indexes
CREATE INDEX IDX_CUSTOMER_NAME ON DIM_CUSTOMER(CUSTOMER_NAME);
CREATE INDEX IDX_CUSTOMER_CITY ON DIM_CUSTOMER(CITY);
CREATE INDEX IDX_PRODUCT_CODE ON DIM_PRODUCT(PRODUCT_CODE);
CREATE INDEX IDX_PRODUCT_CATEGORY ON DIM_PRODUCT(CATEGORY);
CREATE INDEX IDX_ORDER_CUSTOMER ON FACT_ORDER(CUSTOMER_ID);
CREATE INDEX IDX_ORDER_DATE ON FACT_ORDER(ORDER_DATE);
CREATE INDEX IDX_ORDER_NUMBER ON FACT_ORDER(ORDER_NUMBER);
CREATE INDEX IDX_ORDERLINE_ORDER ON FACT_ORDER_LINE(ORDER_ID);
CREATE INDEX IDX_ORDERLINE_PRODUCT ON FACT_ORDER_LINE(PRODUCT_ID);
